### ISSUE TITLE
Log Level support

### ISSUE THREAD

**Issue by BugsBunnyBR** [facebookincubator/spectrum#180]
Is Verbose log level not supported? The check below uses DEBUG, but the lowest value is VERBOSE and this makes the lib crash when VERBOSE is used.

```
private static boolean isValidLogLevel(final int level) {
    return level >= Log.DEBUG && level <= Log.ASSERT;
  }
```

````
public static final int VERBOSE = 2;

    /**
     * Priority constant for the println method; use Log.d.
     */
    public static final int DEBUG = 3;
```

**Comment by lambdapioneer** [comment]
This is indeed not intended and a bug :) feel free to send a PR for fixing this if you like. Otherwise, I'll try to send one in the near future.

**Comment by BugsBunnyBR** [comment]
I am traveling, so it would be better if you don't wait for my pr in the next 3 days. After that I can give it a try.
