### ISSUE TITLE
forceUpOrientation has no effect in the picture

### ISSUE THREAD

**Issue by BugsBunnyBR** [facebookincubator/spectrum#181]
If forceUpOrientation= true in Android.
The image is not being rotated and the returned  ImageOrientation is UP.

Is this something that is in the pipeline? The idea is to use ExifInterface here?

**Comment by cuva** [comment]
@BugsBunnyBR thanks for reporting the issue. Could you provide a repro case for the issue? I.e which encode/transcode options were used along with the image (if possible). Thanks!

**Comment by BugsBunnyBR** [comment]
I think it was my mistake. I displayed the original and the `forceUpOrientation` generated to check if this was working, but both have are displayed "UP", but when printing in logcat can see the data is correct. I think maybe Android rotates the image before showing. I don't know.
Anyway, here is my sample : https://github.com/BugsBunnyBR/spectrum_android_sample
