### ISSUE TITLE
JCenter is at end of life

### ISSUE THREAD

**Issue by alexvasilkov** [facebookincubator/spectrum#1817]
As you probably already know: https://blog.gradle.org/jcenter-shutdown.

It would be nice to migrate the project to Maven Central, and probably even re-publish current version if no new versions are expected soon.

**Comment by MarsVard** [comment]
Too late <3

**Comment by zmroczek** [comment]
Hi all,

Thanks for signaling that, we will be looking into this in January and will keep you posted on the status.

**Comment by pundirAbhishek** [comment]
Hi
Any update on this?

**Comment by zmroczek** [comment]
Once again apologies for the delay - spectrum is available in Maven Central though since January, I will update the release notes: https://repo.maven.apache.org/maven2/com/facebook/spectrum/
