### ISSUE TITLE
Lexical or Preprocessor Issue: 'webp/encode.h' file not found

### ISSUE THREAD

**Issue by GabrielSilveiraa** [facebookincubator/spectrum#187]
Using pod 'SpectrumKit', when I try to build the project, I get the 'webp/encode.h' file not found error. It also happens with the SpectrumKitSample project.

**Comment by rahulvyas** [comment]
I am also having the same issue

**Comment by rahulvyas** [comment]
Does anyone knows any fix ?

**Comment by cuva** [comment]
Hey @rahulvyas & @GabrielSilveiraa 

Have you tried every step of the documentation? (Note the library isn’t currently compatible with ‘use_framework’). 

https://libspectrum.io/docs/getting_started_ios

Let me know.

**Comment by cuva** [comment]
I've just cloned the repo and successfully been able to run `pod install` in the sample app folder, open with Xcode and build & run. Closing this task for now since it seems to be working.
