### ISSUE TITLE
iOS latest pod not working

### ISSUE THREAD

**Issue by alvincrisuy** [facebookincubator/spectrum#190]
I'm encountering an issue when using cocoapods.

<img width="388" alt="Screen Shot 2019-10-04 at 3 43 17 PM" src="https://user-images.githubusercontent.com/7260700/66190110-dea3e080-e6bd-11e9-96be-203dba41cc08.png">
<img width="625" alt="Screen Shot 2019-10-04 at 3 43 42 PM" src="https://user-images.githubusercontent.com/7260700/66190111-dea3e080-e6bd-11e9-94ad-75ec70fa0551.png">

**Comment by cuva** [comment]
Hi @alvincrisuy. Thanks for the interest in Spectrum.

Unfortunately spectrum doesn't work yet with `use_frameworks!` - see #25 and the reference in the docs: https://libspectrum.io/docs/getting_started_ios

Unfortunately this isn't something we've had the time to get to just yet. I'll close the issue for now - but feel free to re-open it if you've got further questions (or comment directly on the #25)
