### ISSUE TITLE
error code 255 for encoding Image

### ISSUE THREAD

**Issue by RachelRWang** [facebookincubator/spectrum#203]
Hi, 
There were some cases failed on encoding process with error code255. Could you provide more info on  error code 255? 
I am using jpeg plug to encode the image.

- (FSPResultData *)encodeImage:(UIImage *)image
                       options:(FSPEncodeOptions *)options
                         error:(NSError **)error

**Comment by diegosanchezr** [comment]
Hi @RachelRWang,

Error code 255 is generic. You can find more details about the userInfo property of the NSError
