### ISSUE TITLE
How to check that SpectrumSoLoader is already loaded

### ISSUE THREAD

**Issue by lkvr** [facebookincubator/spectrum#208]
code:
```
class CameraActivity : AppCompatActivity() {

  private lateinit var mSpectrum: Spectrum

  override fun onCreate(savedInstanceState: Bundle?) {
     
     SpectrumSoLoader.init(this);
     
     mSpectrum = Spectrum.make(SpectrumLogcatLogger(Log.INFO), Array(1) 
  {SpectrumPluginJpeg.get()} );
}

```

after starting camera activity for the second time, I get:

`
SpectrumSoLoader must not be initialized more than once
`

Unfortunately "sAlreadyInitialized" property is private.

What's the proper way to check that library is initialized?
Or the only way is to call "init" this in Application class?

(thanks for great lib, jpeg quality/size is amazing!)

**Comment by AurelC2G** [comment]
Hi!

The documentation recommends initializing spectrum in your `Application` class, not in your activity class. which should work around this double-initialization issue.

By the way, right now by passing `this` (the activity) to `SpectrumSoLoader.init()`, you'll end up leaking your activity! That's in part why we recommend passing in the application instead.

**Comment by lkvr** [comment]
Thanks!


```
 import android.app.Application
 import com.facebook.spectrum.SpectrumSoLoader

 class MyApplication: Application() {
    override fun onCreate() {
        super.onCreate()
        SpectrumSoLoader.init(this);
    }
 }
```


In Applications class it's works just fine.
