### ISSUE TITLE
Image is getting distorted

### ISSUE THREAD

**Issue by rahulvyas** [facebookincubator/spectrum#219]
On iOS 13 images are getting distorted. Anyone knows any fix ? I'm using JPEGPlugin

![IMG_0907](https://user-images.githubusercontent.com/87060/88775450-576eae80-d1a2-11ea-8f69-be896f3ff474.PNG)
![IMG_0933](https://user-images.githubusercontent.com/87060/88775456-5b023580-d1a2-11ea-98f8-a22b343f04c6.PNG)

**Comment by AurelC2G** [comment]
Looks like something wrong with how you're using the library (we're using it without issues on iOS 13). Can you share the code leading to this issue?

**Comment by rahulvyas** [comment]
I'm using following code

```
- (UIImage*)transcodeImage:(UIImage*)image {
    
    FSPSpectrum *spectrum = [[FSPSpectrum alloc] initWithPlugins:@[[FSPJpegPlugin new]]
    configuration:nil];
    
    FSPEncodeRequirement *encodeRequirement =
        [FSPEncodeRequirement encodeRequirementWithFormat:FSPEncodedImageFormat.jpeg
                                                     mode:FSPEncodeRequirementModeLossy
                                                  quality:70];

    FSPTransformations *transformations = [FSPTransformations new];
    transformations.resizeRequirement =
        [[FSPResizeRequirement alloc] initWithMode:FSPResizeRequirementModeExactOrSmaller
                                        targetSize:CGSizeMake(2048, 2048)];

    FSPEncodeOptions *options =
        [FSPEncodeOptions encodeOptionsWithEncodeRequirement:encodeRequirement
                                             transformations:transformations
                                                    metadata:nil
                                               configuration:nil
                         outputPixelSpecificationRequirement:nil];

    NSError *error;
    FSPResultData *result = [spectrum encodeImage:image options:options error:&error];
    if (result.result.didSucceed && result.data) {
        UIImage* image = [UIImage imageWithData:result.data];
        if (image) {
            return image;
        }
    }
    return image;
}
```

**Comment by rahulvyas** [comment]
Update the same code is working on iPhone 6 iOS 12.4.6

**Comment by rahulvyas** [comment]
Update 2 on iOS 12 I'm getting error for the above image

`Error Domain=com.facebook.spectrum Code=255 "(null)" UserInfo={com.facebook.spectrum.error-name=scanline_conversion_unsupported_premultiplied_alpha, com.facebook.spectrum.error-location=facebook::spectrum::core::proc::DynamicScanlineConverter<facebook::spectrum::core::proc::indices::RGB, facebook::spectrum::core::proc::indices::RGB>::DynamicScanlineConverter(const image::pixel::Specification &, const image::pixel::Specification &, const image::Color &) [InputIndices = facebook::spectrum::core::proc::indices::RGB, OutputIndices = facebook::spectrum::core::proc::indices::RGB]:348}`

**Comment by wizh** [comment]
Thanks for reaching out! Could you please clarify whether the first png image you uploaded is the original image that you are transcoding? If yes, have you included the png plugin? If not, could you please upload the original so we can try to reproduce locally? Is this happening for all images that you try to transcode? Are you getting any error logs on iOS 13? And for iOS 12, is it also outputting a distorted image or none at all?

**Comment by rahulvyas** [comment]
@wizh Yes the first image is the original image. NO I'm not using PNG plugin. Yes on iOS 13 happening with All the images.On iOS 12 I'm getting error for this particular image. Rest are working fine on iOS 12. I suspect this issue might be due to picking images from PHAssets. I am pasting code for PHAsset image picking, but I wonder why it worked on iOS 12. Same image is failing on iOS 13 and working on iOS 12. Anyways here is the code for Asset Picking

```
        PHImageManager *imageManager = [[PHImageManager alloc] init];
        PHImageRequestOptions *options = [[PHImageRequestOptions alloc] init];
        options.deliveryMode = PHImageRequestOptionsDeliveryModeFastFormat;//PHImageRequestOptionsDeliveryModeHighQualityFormat;
        options.networkAccessAllowed = YES;
        options.resizeMode = PHImageRequestOptionsResizeModeExact;
        options.synchronous = YES;

      NSMutableArray *mutableImages = [NSMutableArray array];
        for (PHAsset *asset in photoAssets) {
           [imageManager requestImageForAsset:asset
                                   targetSize:PHImageManagerMaximumSize
                                  contentMode:PHImageContentModeDefault
                                      options:options
                                resultHandler:^void(UIImage *image, NSDictionary *info) {
                                    [mutableImages addObject:image];
                                }];
        }
```

**Comment by rahulvyas** [comment]
**Update 2**
I've changed few properties/parameters in PHImageManager code as below

**Changed**
options.deliveryMode = PHImageRequestOptionsDeliveryModeFastFormat;
**To**
options.deliveryMode = PHImageRequestOptionsDeliveryModeHighQualityFormat;



**Changed**
targetSize:PHImageManagerMaximumSize
**To**
targetSize:CGSizeMake(2048,2048)



And for Now it's working on iOS 13 - Device iPhone XR.

**Comment by wizh** [comment]
Sounds like your issue was resolved. Feel free to open a new issue if your issues persist.
