### ISSUE TITLE
"Getting started with iOS" section uses wrong pod name

### ISSUE THREAD

**Issue by marcusbuffett** [facebookincubator/spectrum#22]
In "Getting Started on iOS" in the docs, the instructions say to put the following in your podfile:

```pod 'SpectrumKit/SpectrumKit'```

This fails for me, as cocoapods can't find a pod named `SpectrumKit/SpectrumKit`, should this just be `pod 'SpectrumKit'`, or maybe `pod 'SpectrumCore'`?

**Comment by cuva** [comment]
Thanks for submitting an issue @marcusbuffett. Indeed it should just be `pod 'SpectrumKit'`. I'll be updating the docs soon.

**Comment by cuva** [comment]
Fixed in 4ec6073! Thanks again for the contrib @marcusbuffett!
