### ISSUE TITLE
Maybe it's a BUG？

### ISSUE THREAD

**Issue by LoserForLoser** [facebookincubator/spectrum#28]
![38ea595b-5473-4d81-818b-ffa7aff176c7](https://user-images.githubusercontent.com/17430128/51881707-116f3980-23b7-11e9-8680-7c08bdc290e8.png)
Maybe it's a BUG？
As shown

**Comment by cuva** [comment]
Hi @LoserForLoser. Thanks for reporting this issue. I was able to reproduce it locally.

It does look like we might be accessing a region we're not supposed to when resizing to 2x2 and cropping the top left pixel.

I've taken the liberty to rename the issue to make it clearer and re-opening the issue.

**Comment by chenzhibo** [comment]
does this crash closed?

**Comment by LoserForLoser** [comment]
> does this crash closed?

![Simulator Screen Shot - iPhone XS Max - 2019-03-18 at 14 44 51](https://user-images.githubusercontent.com/17430128/54511641-86f59000-498c-11e9-842c-bb98ef116a60.png)
看样子是暂时做了限制，应该是还没改好

**Comment by cuva** [comment]
Thanks for checking, @LoserForLoser. I don't think we've done anything to fix this crash just yet - would you mind trying with the waterfall-y image and check that it works there as well? It might be somewhat image specific.

Cheers!

**Comment by LoserForLoser** [comment]
Thank you for your reply
I will try it
