### ISSUE TITLE
Add support for progress in Native stream encoding stream

### ISSUE THREAD

**Issue by vipinhelloindia** [facebookincubator/spectrum#30]
Hi , 
We are using Retrofit for Image uploading and wishing to improve image bandwidth over the network.
We have implemented it though found that support for showing progress in notification needed.

Following is the code implementation that works for uploading the image while we do need to calculate content length and we did twice encoding.
   
     `
    import com.facebook.spectrum.EncodedImageSink;
    import com.facebook.spectrum.EncodedImageSource; 
    import com.facebook.spectrum.SpectrumException;
    import com.facebook.spectrum.SpectrumResult;
    import com.facebook.spectrum.image.ImageSize;
    import com.facebook.spectrum.options.TranscodeOptions;
    import com.facebook.spectrum.requirements.EncodeRequirement;
    import com.facebook.spectrum.requirements.ResizeRequirement;
    import com.jeevansathi.android.activities.JS;
    import com.jeevansathi.android.utils.JsLog;

    import java.io.ByteArrayOutputStream;
    import java.io.File;
    import java.io.IOException;
    import java.io.OutputStream;

    import okhttp3.MediaType;
    import okhttp3.MultipartBody;
    import okhttp3.RequestBody;
    import okio.BufferedSink;

    import static com.facebook.spectrum.image.EncodedImageFormat.JPEG;

    public class ProgressRequestBody extends RequestBody {
    private static final int DEFAULT_BUFFER_SIZE = 8192;
    private File mFile;
    private UploadProgressCallback mListener;
    byte[] mContent;

    public ProgressRequestBody(final File finalPhoto, final UploadProgressCallback listener) {
        mFile = finalPhoto;
        mListener = listener;
        initSpectrum();
    }

    private void initSpectrum() {
        final ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            JS.getSpectrum().transcode(
                    EncodedImageSource.from(mFile),
                    EncodedImageSink.from(new OutputStream() {
                        @Override
                        public void write(int b) throws IOException {
                            out.write(b);
                        }
                    }),
                    TranscodeOptions.Builder(new EncodeRequirement(JPEG, 90))
                            .resize(ResizeRequirement.Mode.EXACT_OR_SMALLER, new ImageSize(2018, 2018))
                            .build(),
                    "upload_flow_callsite_identifier");
            mContent = out.toByteArray();
            out.close();
        } catch (SpectrumException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public MediaType contentType() {
        return MultipartBody.FORM;
    }

    @Override
    public long contentLength() throws IOException {
        return mContent.length;
    }

    @Override
    public void writeTo(BufferedSink sink) throws IOException {
        try {
            SpectrumResult result = JS.getSpectrum().transcode(
                    EncodedImageSource.from(mFile),
                    EncodedImageSink.from(sink.outputStream()),
                    TranscodeOptions.Builder(new EncodeRequirement(JPEG, 90))
                            .resize(ResizeRequirement.Mode.EXACT_OR_SMALLER, new ImageSize(2018, 2018))
                            .build(),
                    "upload_flow_callsite_identifier");
            JsLog.d("Result: ", result.toString());
        } catch (SpectrumException e) {
            e.printStackTrace();
        }
    }

    //    @Override
    //    public void writeTo(BufferedSink sink) throws IOException {
    //        long fileLength = mFile.length();
    //        long interval = fileLength / 20;
    //        if (mListener != null) {
    //            mListener.onStartUpload();
    //        }
    //
    //        byte[] buffer = new byte[DEFAULT_BUFFER_SIZE];
    //        FileInputStream in = new FileInputStream(mFile);
    //        long uploaded = 0;
    //        int read;
    //        try {
    //            while ((read = in.read(buffer)) != -1) {
    //                sink.write(buffer, 0, read);
    //                if (mListener != null) {
    //
    //                    uploaded += read;
    //
    //                    if (uploaded >= interval) {
    //                        interval = interval + uploaded;
    //                        mListener.progress((int) fileLength, (int) uploaded);
    //                    }
    //                }
    //            }
    //        } catch (Exception e) {
    //            e.printStackTrace();
    //        } finally {
    //            in.close();
    //        }
    //    }

    }

`

**Comment by lambdapioneer** [comment]
Doing this twice shouldn't be necessary and is definitely not advisable as the output could theoretically change between consecutive calls. Also encoding an image is a computationally intensive operations which will hurt battery life and overall upload time.

A better  way here would be to store the encoded result in the `ByteArrayOutputStream`, keep that one around as a member field during the upload and then pipe the `ByteArrayOutputStream` into the `BufferedSink` for the actual upload operation.

**Comment by vipinhelloindia** [comment]
@lambdapioneer Agree , Initially did the same , I am finding better way in spectrum , or may be in RequestMultiPart in Retrofit .
It is now clear content length and outputstream may vary for each encoding for same image 
Thanks
