### ISSUE TITLE
Update FAQ for performance concerns (parallel computing)

### ISSUE THREAD

**Issue by Ethan1983** [facebookincubator/spectrum#34]
I have used Renderscript in Android for better crop performance than using BitmapRegionDecoder, it was a trade-off between memory and performance.

It is not clear if spectrum offers any similar parallel computing in both Android and iOS. Please update the FAQ for clients to consider using this library.

**Comment by lambdapioneer** [comment]
Hi @Ethan1983, thanks for creating the issue.

I think the cropping of encoded files and the region decoding / bitmap cropping compare quite different flows. I'd be inclined to say that mentioning RenderScript might raise more confusion with a reader about the fact that Spectrum mainly caters encoded images.

What do you think?

**Comment by Ethan1983** [comment]
It wasn't an apples to apples comparison just to point that parallel processing (Renderscript, Pixel Visual core DSPs, CUDA) helps reduce processing time. It would be good if performance trade off was documented and if there is any opt-in/opt-out API for clients in the encoding pipeline.

Based on this presentation, it seems like performance is traded for low size.
https://youtu.be/Lb5H6_vCEok?t=1639

**Comment by lambdapioneer** [comment]
Hey @Ethan1983, I've added an item to the FAQ :) thanks for the suggestion
