### ISSUE TITLE
Source code to ask

### ISSUE THREAD

**Issue by LoserForLoser** [facebookincubator/spectrum#35]
Hello there
Due to our company's regulations, it is not possible to integrate Spectrum through cocoapods
So you need to manually pour the source file
I don't know what to do, please guide if you can.
Thank you

**Comment by cuva** [comment]
Hey @LoserForLoser 

Thanks for reaching out. If I'm understanding correctly you'd like to integrate Spectrum as a dependency to your iOS project w/o using Cocoapods.

This isn't a flow we've tested or that we officially support - we generally recommend integrating Spectrum through CP or Carthage (work in progress). That being said, it should be possible to create an Xcode project for `SpectrumKit` and its dependencies. It would requires producing all the Xcode projects needed for each target dependencies (folly, mozjpeg, libpng, libwebp) as well as `SpectrumCore` & `SpectrumKit`.

Does this make sense?

**Comment by LoserForLoser** [comment]
Hey @cuva 
I have seen your reply
I have received and clarified how to use
Thank you for your guidance

**Comment by LoserForLoser** [comment]
Hey @cuva
I have a problem when I use source code directly. How do I get the code for SpectrumCore? I only found the code for SpectrumKit in Spectrum.
I have now sourced folly, mozjpeg, libpng, libwebp.
Please give detailed instructions.
Thank you!

**Comment by cuva** [comment]
Hi @LoserForLoser 

The code for SpectrumCore is located in `cpp/spectrum`. This relates to the C++ core of Spectrum while `SpectrumKit` refers to the objective-c layer on top of it. Does this help?

**Comment by LoserForLoser** [comment]
Hey @cuva
I think I already know what you mean.
If there is anything wrong, please point out.
As shown
Thank you for your reply
![图片](https://user-images.githubusercontent.com/17430128/54577565-3e46e100-4a37-11e9-84c1-94db73eee7b5.png)
![图片](https://user-images.githubusercontent.com/17430128/54577570-430b9500-4a37-11e9-9ee1-c5082354b6df.png)

**Comment by cuva** [comment]
This looks correct. What's the issue you're experiencing?

**Comment by LoserForLoser** [comment]
Thank you for your help
For the time being, Spectrum has no problem here.
At the moment, I need to make adjustments to the other four frameworks.
If I have a problem, I may ask for help again.
hope I did not disturb you
Thank you

**Comment by LoserForLoser** [comment]
Hey @cuva
Thank you for your answer
In fact, I did have a problem. I reported this error when I was using libpng.
I don't know what's going on, I didn't find a viable solution on Google.
I don't know if you can help me again?
I have submitted a Issue under libpng but have not yet received a reply
Https://github.com/glennrp/libpng/issues/281
Thank you very much
![图片](https://user-images.githubusercontent.com/17430128/54673831-17bb9f80-4b36-11e9-8761-b33ff3ec64d7.png)

**Comment by LoserForLoser** [comment]
> Hey @cuva
> Thank you for your answer
> In fact, I did have a problem. I reported this error when I was using libpng.
> I don't know what's going on, I didn't find a viable solution on Google.
> I don't know if you can help me again?
> I have submitted a Issue under libpng but have not yet received a reply
> [Https://github.com/glennrp/libpng/issues/281](Https://github.com/glennrp/libpng/issues/281)
> Thank you very much
> ![图片](https://user-images.githubusercontent.com/17430128/54673831-17bb9f80-4b36-11e9-8761-b33ff3ec64d7.png)

In addition, if my Shared Project Settings is modified as shown in the figure, the following error will be reported.
Make: *** No targets specified and no makefile found. Stop.
Command /usr/bin/make failed with exit code 2
![图片](https://user-images.githubusercontent.com/17430128/54676543-e0e88800-4b3b-11e9-8acb-be6b5fa830e6.png)

**Comment by LoserForLoser** [comment]
Hey @cuva 
Thank you for your patience
But I have encountered some other problems here.
I don't know if you tried to directly introduce the source code of folly, mozjpeg, libpng, libwebp when you wrote Spectrum.
Now I am experiencing the problem with the adjustment of libpng
I am now trying to install ncurses-6.1 to fix it.
I don't know if you have any experience to help me use them.
I hope I have not bothered you
Thank you
![图片](https://user-images.githubusercontent.com/17430128/54733175-27d58c80-4bd3-11e9-806b-5e60c9a2cee4.png)
