### ISSUE TITLE
Can not compress the picture properly, there is purple phenomenon

### ISSUE THREAD

**Issue by chenzhibo** [facebookincubator/spectrum#39]
Hello,
when i encode one jpeg 64*48,  i Can not compress the picture properly, there is purple phenomenon。
![574582621 587397](https://user-images.githubusercontent.com/6214276/54511408-e99a5c00-498b-11e9-85d2-f6c1ced3edb8.jpg)
![574582625 446061](https://user-images.githubusercontent.com/6214276/54511410-ea32f280-498b-11e9-8706-5c9e5f7f6940.jpg)
![574582626 228842](https://user-images.githubusercontent.com/6214276/54511413-eacb8900-498b-11e9-861a-bd0726d4d6ba.jpg)

**Comment by chenzhibo** [comment]
[[PHImageManager defaultManager] requestImageDataForAsset:asset options:requestOptions resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
                
                FSPEncodeRequirement *encodeRequirement =
                [FSPEncodeRequirement encodeRequirementWithFormat:FSPEncodedImageFormat.jpeg];
                FSPEncodeOptions *options =
                [FSPEncodeOptions encodeOptionsWithEncodeRequirement:encodeRequirement];
                
                FSPResult *data = [[FSPSpectrum sharedInstance] encodeImage:imageData toFileAtURL:[NSURL fileURLWithPath:path]  options:options error:&error];

**Comment by lambdapioneer** [comment]
Hi @chenzhibo , thanks for opening the issue. Can you share the image that you as input for `requestImageDataForAsset`? That will help us reproducing the issue :)

**Comment by chenzhibo** [comment]
![CD7122E7-639E-4779-87BF-43EC69EADF93_20190318191947](https://user-images.githubusercontent.com/6214276/54526840-ff6f4780-49b2-11e9-88bb-01c013b7941d.jpeg)

**Comment by chenzhibo** [comment]
PHImageRequestOptions *requestOptions = [[PHImageRequestOptions alloc] init];
    requestOptions.resizeMode = PHImageRequestOptionsResizeModeExact;
    requestOptions.deliveryMode = PHImageRequestOptionsDeliveryModeHighQualityFormat;
    requestOptions.synchronous = YES;
    targetSize = CGSizeMake(64, 64);
    requestOptions.networkAccessAllowed = YES;
    [[PHImageManager defaultManager] requestImageForAsset:asset targetSize:targetSize contentMode:contentMode options:requestOptions resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {
FSPEncodeRequirement *encodeRequirement =
            [FSPEncodeRequirement encodeRequirementWithFormat:FSPEncodedImageFormat.jpeg];
            FSPEncodeOptions *options =
            [FSPEncodeOptions encodeOptionsWithEncodeRequirement:encodeRequirement];
            
            FSPResult *data = [[FSPSpectrum sharedInstance] encodeImage:imageData toFileAtURL:[NSURL fileURLWithPath:path]  options:options error:&error];

**Comment by cuva** [comment]
Hi @chenzhibo 

Could you confirm on which platform this happens? Was it on a device or simulator? If a device, which one?

Many thanks!

**Comment by diegosanchezr** [comment]
Hi @chenzhibo,

I debugged this problem and found that these small images are encoded with kCGImagePixelFormatRGB555.

Unfortunately, Spectrum doesn't support this kind of format for now. I made some changes in 15fb5fdc5988310ffc20b9eb5195dff5f3c7c3cd to detect this case and make sure we return an error.

Feel free to open a new issue to add support for kCGImagePixelFormatRGB555.
