### ISSUE TITLE
Does the Android library support arm64-v8a ABI?

### ISSUE THREAD

**Issue by gpartida** [facebookincubator/spectrum#40]
I have built an android app that uses the Spectrum library and it is working great except when I try to install the APK that is generated for arm64-v8a ABI target devices (using a Motorola Moto E4) I get the following error: [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113] when trying to run the adb install command. I followed the documentation and included 

```
splits {
   abi {
     // Enables building multiple APKs per ABI.
     enable true

     // By default all ABIs are included, so use reset() and include to specify that we only
     // want APKs for "x86", "x86_64", "arm64-v8a", "armeabi-v7a".

     // Resets the list of ABIs that Gradle should create APKs for to none.
     reset()

     // Specifies a list of ABIs that Gradle should create APKs for.
     include "x86", "x86_64", "arm64-v8a", "armeabi-v7a"

     // Specifies that we do not want to also generate a universal APK that includes all ABIs.
      universalApk false
   }
 }
```

under the android section of my app's build.gradle file and I can see that if I build the APK's i do get all the desired architecture specific apks in my build outputs folder:

```
app-arm64-v8a-debug.apk
app-armeabi-v7a-debug.apk
app-x86_64-debug.apk
app-x86-debug.apk

```
But when I try to install the app-arm64-v8a-debug.apk onto my arm64 device I get the error above. If I instead try and install the app-armeabi-v7a-debug.apk everything works, but my device should support the arm64-v8a ABI target.

**Comment by gpartida** [comment]
Hmm, even though the specs for this phone tell me CPU is a quad core 64 bit processor, running 

`adb -s [MOTOE4SerialNumber] shell getprop |grep abi`

Returns:
```
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
```

So my bad. Closing issue.

**Comment by lambdapioneer** [comment]
Glad you were able to solve this :) Spectrum indeed should work fine on aarch64. Feel free to update if you experience something surprising.

**Comment by pubut** [comment]
offcourse yes, official release Qt5.12.0 provide android armeabi-v7a and arm64-v8a env, just try it!
