### ISSUE TITLE
Processing should either remove or update jpg-exif-thumbnail in output jpg

### ISSUE THREAD

**Issue by k3b** [facebookincubator/spectrum#41]
After cropping a jpg with EncodeRequirement.Mode.LOSSLESS the result picture was cropped as expected and source meta data (exif, iptc, xmp) was copied to the cropped destination jpg, including the original jpg-exif-thumbnail 

I would either expect that the cropped image has no jpg-exif -thumbnail or an updated thumbnail.

As a result my android filemanger shows a preview of the original image and not of the cropped on.

I am using 

    implementation 'com.facebook.spectrum:spectrum-core:1.0.0'
    implementation 'com.facebook.spectrum:spectrum-jpeg:1.0.0'

**Comment by lambdapioneer** [comment]
Hi @k3b, that is a very valid point. The behaviour to achieve this would go here:

https://github.com/facebookincubator/spectrum/blob/master/cpp/spectrum/core/decisions/MetadataDecision.cpp#L13-L31

I will mark this as a standing bug and hope to have a look soon

**Comment by cuva** [comment]
Fixed in a662be47b29f3864b3f015b86ab34d0b1c2aba29 - awaiting for release. Thanks for the report @k3b

**Comment by jungilhan** [comment]
Hi, @lambdapioneer, @cuva 
If you don't mind, can I know when the next version is coming out? I'm looking forward this patch. 🤓

**Comment by k3b** [comment]
https://github.com/facebookincubator/spectrum/releases/tag/v1.2.0  fixed https://github.com/k3b/LosslessJpgCrop/issues/4
